version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: catalogo-service-dev
    container_name: catalogo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env.docker  # ‚Üê Cambia esto
    networks:
      - catalogo-network

  webserver:
    image: nginx:alpine
    container_name: catalogo-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - catalogo-network

  db:
    image: mysql:8.0
    container_name: catalogo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_catalogo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: sail
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - catalogo-network

  redis:
    image: redis:alpine
    container_name: catalogo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - catalogo-network

volumes:
  dbdata:

networks:
  catalogo-network:
    driver: bridge